### PR TITLE
Use latest snapshot in main

### PR DESCRIPTION
**Pull request by fantkolja**
All other docs repos use a special "snapshot" version in the `main` branch (e.g. [operator-docs](https://github.com/hazelcast/hazelcast-platform-operator-docs/blob/main/docs/antora.yml)).
It helps against a casual version collision (e.g. while [checking](https://github.com/hazelcast/clc-docs/actions/runs/11916108282/job/33207986644?pr=42) internal links) among branches.
This PR will have no impact on production docs, since we are using only `v/*` branches of this repo in docs

### CODE REVIEW

**Review by oliverhowell — APPROVED** [review]

**Comment by yuce** [comment]
I wonder whether there's a better way.
This change will require us to send a commit to the `v/*` branches just to update the version.

**Comment by fantkolja** [comment]
> I wonder whether there's a better way. This change will require us to send a commit to the `v/*` branches just to update the version.

Could you please explain the release flow now? I see you already have the branch `v/5.5.0`. I assume if the branch is there, the version was released. However, the `main` also has the version `5.5.0`, which means that the work on 5.5.0 continues. 
I assume that the `main` branch should have the next version to be released. If we know the exact version which will be released next (e.g. 5.6.0), we could already add it in `main`. If we don't know we could use `snapshot` and change it to the real next version later on when we know it.

**Comment by fantkolja** [comment]
WIll try to do a workaround [here](https://github.com/hazelcast/hazelcast-docs/pull/424) to not change anything in the release process

**Comment by fantkolja** [comment]
The workaround https://github.com/hazelcast/hazelcast-docs/pull/424 did help, so no need to change the versions in the `main` branch

**Comment by yuce** [comment]
Thanks @fantkolja !

**Pull request closed without merging**
